# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './liquidswap/gui/ui/windowpropose.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProposeWindow(object):
    def setupUi(self, ProposeWindow):
        ProposeWindow.setObjectName("ProposeWindow")
        ProposeWindow.resize(800, 500)
        ProposeWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(ProposeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem)
        self.verticalLayoutSend = QtWidgets.QVBoxLayout()
        self.verticalLayoutSend.setObjectName("verticalLayoutSend")
        self.labelSend = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelSend.setFont(font)
        self.labelSend.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSend.setObjectName("labelSend")
        self.verticalLayoutSend.addWidget(self.labelSend)
        self.gridLayoutSend = QtWidgets.QGridLayout()
        self.gridLayoutSend.setObjectName("gridLayoutSend")
        self.comboBoxSendAsset = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxSendAsset.setObjectName("comboBoxSendAsset")
        self.gridLayoutSend.addWidget(self.comboBoxSendAsset, 0, 1, 1, 1)
        self.labelSendAsset = QtWidgets.QLabel(self.centralwidget)
        self.labelSendAsset.setObjectName("labelSendAsset")
        self.gridLayoutSend.addWidget(self.labelSendAsset, 0, 0, 1, 1)
        self.labelSendAmount = QtWidgets.QLabel(self.centralwidget)
        self.labelSendAmount.setObjectName("labelSendAmount")
        self.gridLayoutSend.addWidget(self.labelSendAmount, 1, 0, 1, 1)
        self.horizontalLayoutSendAmount = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSendAmount.setObjectName("horizontalLayoutSendAmount")
        self.lineEditSendAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSendAmount.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditSendAmount.setInputMask("")
        self.lineEditSendAmount.setText("")
        self.lineEditSendAmount.setMaxLength(20)
        self.lineEditSendAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditSendAmount.setObjectName("lineEditSendAmount")
        self.horizontalLayoutSendAmount.addWidget(self.lineEditSendAmount)
        self.labelSendAvailable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSendAvailable.sizePolicy().hasHeightForWidth())
        self.labelSendAvailable.setSizePolicy(sizePolicy)
        self.labelSendAvailable.setText("")
        self.labelSendAvailable.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelSendAvailable.setObjectName("labelSendAvailable")
        self.horizontalLayoutSendAmount.addWidget(self.labelSendAvailable)
        self.gridLayoutSend.addLayout(self.horizontalLayoutSendAmount, 1, 1, 1, 1)
        self.verticalLayoutSend.addLayout(self.gridLayoutSend)
        self.verticalLayoutMain.addLayout(self.verticalLayoutSend)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem1)
        self.verticalLayoutReceive = QtWidgets.QVBoxLayout()
        self.verticalLayoutReceive.setObjectName("verticalLayoutReceive")
        self.labelReceive = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelReceive.setFont(font)
        self.labelReceive.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReceive.setObjectName("labelReceive")
        self.verticalLayoutReceive.addWidget(self.labelReceive)
        self.gridLayoutReceive = QtWidgets.QGridLayout()
        self.gridLayoutReceive.setObjectName("gridLayoutReceive")
        self.labelReceiveAmount = QtWidgets.QLabel(self.centralwidget)
        self.labelReceiveAmount.setMinimumSize(QtCore.QSize(0, 0))
        self.labelReceiveAmount.setObjectName("labelReceiveAmount")
        self.gridLayoutReceive.addWidget(self.labelReceiveAmount, 1, 0, 1, 1)
        self.horizontalLayoutReceiveAsset = QtWidgets.QHBoxLayout()
        self.horizontalLayoutReceiveAsset.setObjectName("horizontalLayoutReceiveAsset")
        self.comboBoxReceiveAsset = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxReceiveAsset.setObjectName("comboBoxReceiveAsset")
        self.horizontalLayoutReceiveAsset.addWidget(self.comboBoxReceiveAsset)
        self.buttonReceiveAddNew = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReceiveAddNew.sizePolicy().hasHeightForWidth())
        self.buttonReceiveAddNew.setSizePolicy(sizePolicy)
        self.buttonReceiveAddNew.setObjectName("buttonReceiveAddNew")
        self.horizontalLayoutReceiveAsset.addWidget(self.buttonReceiveAddNew)
        self.gridLayoutReceive.addLayout(self.horizontalLayoutReceiveAsset, 0, 1, 1, 1)
        self.labelReceiveAsset = QtWidgets.QLabel(self.centralwidget)
        self.labelReceiveAsset.setObjectName("labelReceiveAsset")
        self.gridLayoutReceive.addWidget(self.labelReceiveAsset, 0, 0, 1, 1)
        self.horizontalLayoutReceiveAmount = QtWidgets.QHBoxLayout()
        self.horizontalLayoutReceiveAmount.setObjectName("horizontalLayoutReceiveAmount")
        self.lineEditReceiveAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditReceiveAmount.setText("")
        self.lineEditReceiveAmount.setMaxLength(20)
        self.lineEditReceiveAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditReceiveAmount.setObjectName("lineEditReceiveAmount")
        self.horizontalLayoutReceiveAmount.addWidget(self.lineEditReceiveAmount)
        self.labelReceiveAvailable = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelReceiveAvailable.sizePolicy().hasHeightForWidth())
        self.labelReceiveAvailable.setSizePolicy(sizePolicy)
        self.labelReceiveAvailable.setText("")
        self.labelReceiveAvailable.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelReceiveAvailable.setObjectName("labelReceiveAvailable")
        self.horizontalLayoutReceiveAmount.addWidget(self.labelReceiveAvailable)
        self.gridLayoutReceive.addLayout(self.horizontalLayoutReceiveAmount, 1, 1, 1, 1)
        self.verticalLayoutReceive.addLayout(self.gridLayoutReceive)
        self.verticalLayoutMain.addLayout(self.verticalLayoutReceive)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.buttonGenerateProposal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonGenerateProposal.sizePolicy().hasHeightForWidth())
        self.buttonGenerateProposal.setSizePolicy(sizePolicy)
        self.buttonGenerateProposal.setMinimumSize(QtCore.QSize(160, 50))
        self.buttonGenerateProposal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonGenerateProposal.setObjectName("buttonGenerateProposal")
        self.horizontalLayout.addWidget(self.buttonGenerateProposal)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayoutMain.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayoutMain, 0, 0, 1, 1)
        ProposeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ProposeWindow)
        self.statusbar.setObjectName("statusbar")
        ProposeWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(ProposeWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAuthentication = QtWidgets.QMenu(self.menuEdit)
        self.menuAuthentication.setStatusTip("")
        self.menuAuthentication.setObjectName("menuAuthentication")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        ProposeWindow.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(ProposeWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionAbout = QtWidgets.QAction(ProposeWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConf = QtWidgets.QAction(ProposeWindow)
        self.actionConf.setEnabled(False)
        self.actionConf.setObjectName("actionConf")
        self.actionURL = QtWidgets.QAction(ProposeWindow)
        self.actionURL.setEnabled(False)
        self.actionURL.setObjectName("actionURL")
        self.actionExit = QtWidgets.QAction(ProposeWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuAuthentication.addAction(self.actionConf)
        self.menuAuthentication.addAction(self.actionURL)
        self.menuEdit.addAction(self.menuAuthentication.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(ProposeWindow)
        QtCore.QMetaObject.connectSlotsByName(ProposeWindow)

    def retranslateUi(self, ProposeWindow):
        _translate = QtCore.QCoreApplication.translate
        ProposeWindow.setWindowTitle(_translate("ProposeWindow", "Liquid Asset Swap - Propose a Swap [1/3]"))
        self.labelSend.setText(_translate("ProposeWindow", "Send"))
        self.labelSendAsset.setText(_translate("ProposeWindow", "Asset:"))
        self.labelSendAmount.setText(_translate("ProposeWindow", "Amount:"))
        self.labelReceive.setText(_translate("ProposeWindow", "Receive"))
        self.labelReceiveAmount.setText(_translate("ProposeWindow", "Amount:"))
        self.buttonReceiveAddNew.setStatusTip(_translate("ProposeWindow", "Add a new asset."))
        self.buttonReceiveAddNew.setText(_translate("ProposeWindow", "Add New Asset"))
        self.labelReceiveAsset.setText(_translate("ProposeWindow", "Asset:"))
        self.buttonGenerateProposal.setStatusTip(_translate("ProposeWindow", "Generate proposal with the details specified above."))
        self.buttonGenerateProposal.setText(_translate("ProposeWindow", "Generate Proposal"))
        self.menuFile.setTitle(_translate("ProposeWindow", "File"))
        self.menuEdit.setTitle(_translate("ProposeWindow", "Edit"))
        self.menuAuthentication.setTitle(_translate("ProposeWindow", "Authentication"))
        self.menuHelp.setTitle(_translate("ProposeWindow", "Help"))
        self.actionNew.setText(_translate("ProposeWindow", "Start Over"))
        self.actionNew.setShortcut(_translate("ProposeWindow", "Ctrl+N"))
        self.actionAbout.setText(_translate("ProposeWindow", "About"))
        self.actionAbout.setShortcut(_translate("ProposeWindow", "Ctrl+H"))
        self.actionConf.setText(_translate("ProposeWindow", "Specify liquid.conf…"))
        self.actionConf.setShortcut(_translate("ProposeWindow", "Ctrl+Shift+C"))
        self.actionURL.setText(_translate("ProposeWindow", "Liquid Node URL…"))
        self.actionURL.setShortcut(_translate("ProposeWindow", "Ctrl+Shift+U"))
        self.actionExit.setText(_translate("ProposeWindow", "Exit"))
        self.actionExit.setShortcut(_translate("ProposeWindow", "Ctrl+Q"))

