# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './liquidswap/gui/ui/windowaccept.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AcceptWindow(object):
    def setupUi(self, AcceptWindow):
        AcceptWindow.setObjectName("AcceptWindow")
        AcceptWindow.resize(800, 500)
        AcceptWindow.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(AcceptWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem)
        self.verticalLayoutProposer = QtWidgets.QVBoxLayout()
        self.verticalLayoutProposer.setObjectName("verticalLayoutProposer")
        self.labelProposerTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelProposerTitle.setFont(font)
        self.labelProposerTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProposerTitle.setObjectName("labelProposerTitle")
        self.verticalLayoutProposer.addWidget(self.labelProposerTitle)
        self.gridLayoutProposer = QtWidgets.QGridLayout()
        self.gridLayoutProposer.setObjectName("gridLayoutProposer")
        self.labelProposerAmount = QtWidgets.QLabel(self.centralwidget)
        self.labelProposerAmount.setObjectName("labelProposerAmount")
        self.gridLayoutProposer.addWidget(self.labelProposerAmount, 1, 0, 1, 1)
        self.labelProposerAsset = QtWidgets.QLabel(self.centralwidget)
        self.labelProposerAsset.setObjectName("labelProposerAsset")
        self.gridLayoutProposer.addWidget(self.labelProposerAsset, 0, 0, 1, 1)
        self.labelProposerAssetValue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelProposerAssetValue.sizePolicy().hasHeightForWidth())
        self.labelProposerAssetValue.setSizePolicy(sizePolicy)
        self.labelProposerAssetValue.setText("")
        self.labelProposerAssetValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelProposerAssetValue.setObjectName("labelProposerAssetValue")
        self.gridLayoutProposer.addWidget(self.labelProposerAssetValue, 0, 1, 1, 1)
        self.labelProposerAmountValue = QtWidgets.QLabel(self.centralwidget)
        self.labelProposerAmountValue.setText("")
        self.labelProposerAmountValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelProposerAmountValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelProposerAmountValue.setObjectName("labelProposerAmountValue")
        self.gridLayoutProposer.addWidget(self.labelProposerAmountValue, 1, 1, 1, 1)
        self.verticalLayoutProposer.addLayout(self.gridLayoutProposer)
        self.verticalLayoutMain.addLayout(self.verticalLayoutProposer)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem1)
        self.verticalLayoutReceiver = QtWidgets.QVBoxLayout()
        self.verticalLayoutReceiver.setObjectName("verticalLayoutReceiver")
        self.labelReceiverTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelReceiverTitle.setFont(font)
        self.labelReceiverTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelReceiverTitle.setObjectName("labelReceiverTitle")
        self.verticalLayoutReceiver.addWidget(self.labelReceiverTitle)
        self.gridLayoutReceiver = QtWidgets.QGridLayout()
        self.gridLayoutReceiver.setObjectName("gridLayoutReceiver")
        self.labelReceiverAsset = QtWidgets.QLabel(self.centralwidget)
        self.labelReceiverAsset.setObjectName("labelReceiverAsset")
        self.gridLayoutReceiver.addWidget(self.labelReceiverAsset, 0, 0, 1, 1)
        self.labelReceiverAssetValue = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelReceiverAssetValue.sizePolicy().hasHeightForWidth())
        self.labelReceiverAssetValue.setSizePolicy(sizePolicy)
        self.labelReceiverAssetValue.setText("")
        self.labelReceiverAssetValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelReceiverAssetValue.setObjectName("labelReceiverAssetValue")
        self.gridLayoutReceiver.addWidget(self.labelReceiverAssetValue, 0, 1, 1, 1)
        self.labelReceiverAmountValue = QtWidgets.QLabel(self.centralwidget)
        self.labelReceiverAmountValue.setText("")
        self.labelReceiverAmountValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelReceiverAmountValue.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.labelReceiverAmountValue.setObjectName("labelReceiverAmountValue")
        self.gridLayoutReceiver.addWidget(self.labelReceiverAmountValue, 1, 1, 1, 1)
        self.labelReceiverAmount = QtWidgets.QLabel(self.centralwidget)
        self.labelReceiverAmount.setObjectName("labelReceiverAmount")
        self.gridLayoutReceiver.addWidget(self.labelReceiverAmount, 1, 0, 1, 1)
        self.verticalLayoutReceiver.addLayout(self.gridLayoutReceiver)
        self.verticalLayoutMain.addLayout(self.verticalLayoutReceiver)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem2)
        self.horizontalLayoutBottom = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBottom.setObjectName("horizontalLayoutBottom")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBottom.addItem(spacerItem3)
        self.buttonAccept = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAccept.sizePolicy().hasHeightForWidth())
        self.buttonAccept.setSizePolicy(sizePolicy)
        self.buttonAccept.setMinimumSize(QtCore.QSize(160, 50))
        self.buttonAccept.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonAccept.setObjectName("buttonAccept")
        self.horizontalLayoutBottom.addWidget(self.buttonAccept)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBottom.addItem(spacerItem4)
        self.verticalLayoutMain.addLayout(self.horizontalLayoutBottom)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutMain.addItem(spacerItem5)
        self.gridLayout.addLayout(self.verticalLayoutMain, 0, 0, 1, 1)
        AcceptWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(AcceptWindow)
        self.statusbar.setObjectName("statusbar")
        AcceptWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(AcceptWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAuthentication = QtWidgets.QMenu(self.menuEdit)
        self.menuAuthentication.setObjectName("menuAuthentication")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        AcceptWindow.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(AcceptWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(AcceptWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(AcceptWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConf = QtWidgets.QAction(AcceptWindow)
        self.actionConf.setEnabled(False)
        self.actionConf.setObjectName("actionConf")
        self.actionURL = QtWidgets.QAction(AcceptWindow)
        self.actionURL.setEnabled(False)
        self.actionURL.setObjectName("actionURL")
        self.menuFIle.addAction(self.actionNew)
        self.menuFIle.addSeparator()
        self.menuFIle.addAction(self.actionExit)
        self.menuAuthentication.addAction(self.actionConf)
        self.menuAuthentication.addAction(self.actionURL)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.menuAuthentication.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(AcceptWindow)
        QtCore.QMetaObject.connectSlotsByName(AcceptWindow)

    def retranslateUi(self, AcceptWindow):
        _translate = QtCore.QCoreApplication.translate
        AcceptWindow.setWindowTitle(_translate("AcceptWindow", "Liquid Asset Swap - Accept a Swap [2/3]"))
        self.labelProposerTitle.setText(_translate("AcceptWindow", "Receive"))
        self.labelProposerAmount.setText(_translate("AcceptWindow", "Amount:"))
        self.labelProposerAsset.setText(_translate("AcceptWindow", "Asset:"))
        self.labelReceiverTitle.setText(_translate("AcceptWindow", "Send"))
        self.labelReceiverAsset.setText(_translate("AcceptWindow", "Asset:"))
        self.labelReceiverAmount.setText(_translate("AcceptWindow", "Amount:"))
        self.buttonAccept.setStatusTip(_translate("AcceptWindow", "Accept proposal and fund the transaction."))
        self.buttonAccept.setText(_translate("AcceptWindow", "Accept Proposal"))
        self.menuFIle.setTitle(_translate("AcceptWindow", "File"))
        self.menuEdit.setTitle(_translate("AcceptWindow", "Edit"))
        self.menuAuthentication.setTitle(_translate("AcceptWindow", "Authentication"))
        self.menuHelp.setTitle(_translate("AcceptWindow", "Help"))
        self.actionNew.setText(_translate("AcceptWindow", "Start Over"))
        self.actionNew.setShortcut(_translate("AcceptWindow", "Ctrl+N"))
        self.actionExit.setText(_translate("AcceptWindow", "Exit"))
        self.actionExit.setShortcut(_translate("AcceptWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("AcceptWindow", "About"))
        self.actionAbout.setShortcut(_translate("AcceptWindow", "Ctrl+H"))
        self.actionConf.setText(_translate("AcceptWindow", "Specify liquid.conf…"))
        self.actionConf.setShortcut(_translate("AcceptWindow", "Ctrl+Shift+C"))
        self.actionURL.setText(_translate("AcceptWindow", "Liquid Node URL…"))
        self.actionURL.setShortcut(_translate("AcceptWindow", "Ctrl+Shift+U"))

