# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './liquidswap/gui/ui/windowstart.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StartWindow(object):
    def setupUi(self, StartWindow):
        StartWindow.setObjectName("StartWindow")
        StartWindow.setWindowModality(QtCore.Qt.WindowModal)
        StartWindow.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StartWindow.sizePolicy().hasHeightForWidth())
        StartWindow.setSizePolicy(sizePolicy)
        StartWindow.setMinimumSize(QtCore.QSize(800, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icons/app-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StartWindow.setWindowIcon(icon)
        StartWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(StartWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonStart = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStart.sizePolicy().hasHeightForWidth())
        self.buttonStart.setSizePolicy(sizePolicy)
        self.buttonStart.setMinimumSize(QtCore.QSize(160, 50))
        self.buttonStart.setToolTip("")
        self.buttonStart.setObjectName("buttonStart")
        self.verticalLayout.addWidget(self.buttonStart)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonContinue = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonContinue.sizePolicy().hasHeightForWidth())
        self.buttonContinue.setSizePolicy(sizePolicy)
        self.buttonContinue.setMinimumSize(QtCore.QSize(160, 50))
        self.buttonContinue.setObjectName("buttonContinue")
        self.verticalLayout.addWidget(self.buttonContinue)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        StartWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StartWindow)
        self.statusbar.setObjectName("statusbar")
        StartWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(StartWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuConfiguration = QtWidgets.QMenu(self.menuBar)
        self.menuConfiguration.setStatusTip("")
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuAuthentication = QtWidgets.QMenu(self.menuConfiguration)
        self.menuAuthentication.setObjectName("menuAuthentication")
        StartWindow.setMenuBar(self.menuBar)
        self.actionNew = QtWidgets.QAction(StartWindow)
        self.actionNew.setEnabled(False)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtWidgets.QAction(StartWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(StartWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionConf = QtWidgets.QAction(StartWindow)
        self.actionConf.setObjectName("actionConf")
        self.actionURL = QtWidgets.QAction(StartWindow)
        self.actionURL.setObjectName("actionURL")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuAuthentication.addAction(self.actionConf)
        self.menuAuthentication.addAction(self.actionURL)
        self.menuConfiguration.addAction(self.menuAuthentication.menuAction())
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuConfiguration.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(StartWindow)
        QtCore.QMetaObject.connectSlotsByName(StartWindow)

    def retranslateUi(self, StartWindow):
        _translate = QtCore.QCoreApplication.translate
        StartWindow.setWindowTitle(_translate("StartWindow", "Liquid Asset Swap"))
        self.buttonStart.setStatusTip(_translate("StartWindow", "Start a swap."))
        self.buttonStart.setText(_translate("StartWindow", "Start New Swap"))
        self.buttonContinue.setStatusTip(_translate("StartWindow", "Analyze and accept a swap proposal."))
        self.buttonContinue.setText(_translate("StartWindow", "Continue Swap"))
        self.menuFile.setTitle(_translate("StartWindow", "File"))
        self.menuHelp.setTitle(_translate("StartWindow", "Help"))
        self.menuConfiguration.setTitle(_translate("StartWindow", "Edit"))
        self.menuAuthentication.setTitle(_translate("StartWindow", "Authentication"))
        self.actionNew.setText(_translate("StartWindow", "Start Over"))
        self.actionNew.setShortcut(_translate("StartWindow", "Ctrl+N"))
        self.actionExit.setText(_translate("StartWindow", "Exit"))
        self.actionExit.setShortcut(_translate("StartWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("StartWindow", "About"))
        self.actionAbout.setShortcut(_translate("StartWindow", "Ctrl+H"))
        self.actionConf.setText(_translate("StartWindow", "Specify liquid.conf…"))
        self.actionConf.setShortcut(_translate("StartWindow", "Ctrl+Shift+C"))
        self.actionURL.setText(_translate("StartWindow", "Liquid node URL…"))
        self.actionURL.setShortcut(_translate("StartWindow", "Ctrl+Shift+U"))

from liquidswap.gui import resource_rc
